build[api] Fix permissions in services/api/entrypoint.sh
Make entrypoint.sh executable to fix a failure during docker build:

```
Creating aktify_api_1      ... error

ERROR: for aktify_api_1  Cannot start service api: OCI runtime create
failed: container_linux.go:349: starting container process caused
"exec: \"./entrypoint.sh\": permission denied": unknown

```